apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: a.barry@telemaque.fr
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: secure-prodkey
    solvers:
    - http01:
        ingress:
          class: traefik-cert-manager